[package]
name = "skull"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.19.8"

[dependencies]
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
# lalrpop-util = "0.19.8"
regex = "1"
either = "1.8.0"
